# Generated by Django 3.0.5 on 2020-05-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cartmodel_itemname'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='itemValue',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
