# Generated by Django 3.0.5 on 2020-06-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_salesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmodel',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
